# Generated by Django 3.1.6 on 2021-04-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='accepted_status',
            field=models.CharField(blank=True, choices=[('applied', 'applied'), ('confirmed', 'confirmed')], default='applied', max_length=20),
        ),
    ]
