# Generated by Django 3.1.6 on 2021-04-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_auto_20210410_1417'),
        ('applications', '0002_auto_20210410_1345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
