# Generated by Django 3.1.8 on 2021-05-13 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_career_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='posted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
