# Generated by Django 3.1.6 on 2021-02-27 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=20)),
                ('where', models.CharField(choices=[('Virtual', 'Virtual'), ('In-Person', 'In-Person')], max_length=20)),
                ('new_career', models.CharField(blank=True, max_length=30)),
                ('pay', models.CharField(blank=True, max_length=20)),
                ('time_commitment', models.CharField(max_length=20)),
                ('location', models.TextField(blank=True)),
                ('application_deadline', models.DateTimeField()),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True)),
                ('acceptances', models.ManyToManyField(blank=True, related_name='acceptances', to=settings.AUTH_USER_MODEL)),
                ('applications', models.ManyToManyField(blank=True, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('career', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='marketplace.career')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to=settings.AUTH_USER_MODEL)),
                ('rejections', models.ManyToManyField(blank=True, related_name='rejections', to=settings.AUTH_USER_MODEL)),
                ('saves', models.ManyToManyField(blank=True, related_name='saves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
