# Generated by Django 3.1.6 on 2021-02-14 22:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='applications',
            field=models.ManyToManyField(related_name='application', to=settings.AUTH_USER_MODEL),
        ),
    ]
