# Generated by Django 3.1.6 on 2021-02-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(default='title', max_length=20),
            preserve_default=False,
        ),
    ]
