# Generated by Django 3.1.6 on 2021-02-16 03:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0002_listing_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
