# Generated by Django 3.1.6 on 2021-02-28 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_listing_application_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 2, 28, 13, 43, 23, 528182), null=True),
        ),
    ]
