# Generated by Django 3.1.6 on 2021-02-28 18:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_listing_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
