# Generated by Django 3.1.6 on 2021-02-18 23:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0004_listing_saves'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='acceptances',
            field=models.ManyToManyField(blank=True, related_name='acceptances', to=settings.AUTH_USER_MODEL),
        ),
    ]
