# Generated by Django 3.1.6 on 2021-02-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20210228_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='data',
            new_name='posted',
        ),
    ]
