# Generated by Django 3.1.6 on 2021-02-21 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_auto_20210220_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='org',
            new_name='company',
        ),
    ]
