# Generated by Django 3.1.6 on 2021-02-28 22:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_auto_20210228_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='posted',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
