# Generated by Django 3.1.6 on 2021-03-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210307_0225'),
        ('marketplace', '0011_auto_20210307_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='employer_acceptances',
            field=models.ManyToManyField(blank=True, related_name='employer_acceptances', to='accounts.EmployerProfile'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='employer_interview_requests',
            field=models.ManyToManyField(blank=True, related_name='employer_interview_requests', to='accounts.EmployerProfile'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='employer_rejections',
            field=models.ManyToManyField(blank=True, related_name='employer_rejections', to='accounts.EmployerProfile'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='student_acceptances',
            field=models.ManyToManyField(blank=True, related_name='student_acceptances', to='accounts.StudentProfile'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='student_interview_requests',
            field=models.ManyToManyField(blank=True, related_name='student_interview_requests', to='accounts.StudentProfile'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='student_rejections',
            field=models.ManyToManyField(blank=True, related_name='student_rejections', to='accounts.StudentProfile'),
        ),
    ]
