# Generated by Django 3.1.6 on 2021-04-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_auto_20210307_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='application_status',
            field=models.CharField(choices=[('none', 'none'), ('applied', 'applied'), ('confirmed', 'confirmed')], default='none', max_length=30),
        ),
    ]
