# Generated by Django 3.1.6 on 2021-04-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20210410_1345'),
        ('marketplace', '0017_listing_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='application_status',
        ),
        migrations.AlterField(
            model_name='listing',
            name='acceptances',
            field=models.ManyToManyField(blank=True, related_name='listing_acceptances', to='applications.Application'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='applications', to='applications.Application'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='employer_acceptances',
            field=models.ManyToManyField(blank=True, related_name='employer_acceptances', to='applications.Application'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='employer_interview_requests',
            field=models.ManyToManyField(blank=True, related_name='employer_interview_requests', to='applications.Application'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='employer_rejections',
            field=models.ManyToManyField(blank=True, related_name='employer_rejections', to='applications.Application'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='interview_requests',
            field=models.ManyToManyField(blank=True, related_name='interviews', to='applications.Application'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rejections',
            field=models.ManyToManyField(blank=True, related_name='listing_rejections', to='applications.Application'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='student_acceptances',
            field=models.ManyToManyField(blank=True, related_name='student_acceptances', to='applications.Application'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='student_interview_requests',
            field=models.ManyToManyField(blank=True, related_name='student_interview_requests', to='applications.Application'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='student_rejections',
            field=models.ManyToManyField(blank=True, related_name='student_rejections', to='applications.Application'),
        ),
    ]
