# Generated by Django 3.1.6 on 2021-04-10 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0018_auto_20210410_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='acceptances',
            field=models.ManyToManyField(blank=True, related_name='listing_acceptances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='employer_acceptances',
            field=models.ManyToManyField(blank=True, related_name='employer_acceptances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='employer_interview_requests',
            field=models.ManyToManyField(blank=True, related_name='employer_interview_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='employer_rejections',
            field=models.ManyToManyField(blank=True, related_name='employer_rejections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='interview_requests',
            field=models.ManyToManyField(blank=True, related_name='interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rejections',
            field=models.ManyToManyField(blank=True, related_name='listing_rejections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='student_acceptances',
            field=models.ManyToManyField(blank=True, related_name='student_acceptances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='student_interview_requests',
            field=models.ManyToManyField(blank=True, related_name='student_interview_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='student_rejections',
            field=models.ManyToManyField(blank=True, related_name='student_rejections', to=settings.AUTH_USER_MODEL),
        ),
    ]
