# Generated by Django 3.1.6 on 2021-04-10 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0019_auto_20210410_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='awaiting_confirm_acceptance',
            field=models.ManyToManyField(blank=True, related_name='awaiting_confirm_acceptance', to=settings.AUTH_USER_MODEL),
        ),
    ]
