# Generated by Django 3.1.6 on 2021-04-10 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0020_listing_awaiting_confirm_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='confirmed_and_awaiting',
            field=models.ManyToManyField(blank=True, related_name='confirmed_and_awaiting', to=settings.AUTH_USER_MODEL),
        ),
    ]
