# Generated by Django 3.1.6 on 2021-04-10 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_listing_confirmed_and_awaiting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='confirmed_and_awaiting',
        ),
    ]
