# Generated by Django 3.1.6 on 2021-02-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='awards_achievements',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='extracurriculars',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='leadership_roles',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='skills',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='volunteering_experience',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='work_exp',
            field=models.TextField(null=True),
        ),
    ]
