# Generated by Django 3.1.6 on 2021-02-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210210_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='org_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
