# Generated by Django 3.1.6 on 2021-02-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_org_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='org_website',
            field=models.URLField(blank=True),
        ),
    ]
