# Generated by Django 3.1.6 on 2021-03-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_auto_20210307_0053'),
        ('accounts', '0005_auto_20210301_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='acceptances',
            field=models.ManyToManyField(related_name='student_acceptances', to='marketplace.Listing'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='rejections',
            field=models.ManyToManyField(related_name='student_rejections', to='marketplace.Listing'),
        ),
    ]
