# Generated by Django 3.1.6 on 2021-03-07 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210307_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='acceptances',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='interview_requests',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='rejections',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='acceptances',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='interview_requests',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='rejections',
        ),
    ]
