# Generated by Django 3.1.6 on 2021-02-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210220_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(max_length=256, null=True, unique=True),
        ),
    ]
