# Generated by Django 3.1.6 on 2021-02-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210220_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='org_name',
        ),
        migrations.AddField(
            model_name='user',
            name='org_name',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
