# Generated by Django 3.1.6 on 2021-02-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210220_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='org_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
