# Generated by Django 3.1.6 on 2021-02-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210220_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employerprofile',
            old_name='org_website',
            new_name='company_website',
        ),
        migrations.RemoveField(
            model_name='user',
            name='org_name',
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
