# Generated by Django 3.1.6 on 2021-02-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_signup', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('meet_url', models.URLField()),
                ('img', models.ImageField(upload_to='events')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('enforce_one', models.TextField(default='Statistics', editable=False, primary_key=True, serialize=False)),
                ('students', models.IntegerField()),
                ('employers', models.IntegerField()),
                ('professionals', models.IntegerField()),
            ],
        ),
    ]
