# Generated by Django 3.1.6 on 2021-02-11 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistics',
        ),
    ]
