# Generated by Django 3.1.6 on 2021-02-06 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='EmailSignup',
        ),
        migrations.RenameField(
            model_name='emailsignup',
            old_name='email',
            new_name='email_signup',
        ),
    ]
