# Generated by Django 3.1.6 on 2021-03-10 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSignup',
        ),
    ]
