# Generated by Django 3.1.6 on 2021-02-21 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_statistics'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('name', 'meet_url')},
        ),
    ]
