# Generated by Django 3.1.6 on 2021-04-21 02:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_emailsignup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=cloudinary.models.CloudinaryField(default='logo-small_zxmfbe.png', max_length=255, verbose_name='Image'),
        ),
    ]
