# Generated by Django 3.1.6 on 2021-02-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210206_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.IntegerField()),
                ('employers', models.IntegerField()),
                ('professionals', models.IntegerField()),
            ],
        ),
    ]
