# Generated by Django 3.1.6 on 2021-02-21 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210220_2123'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set(),
        ),
    ]
