# Generated by Django 3.1.6 on 2021-02-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_statistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='id',
        ),
        migrations.AddField(
            model_name='statistics',
            name='enforce_one',
            field=models.TextField(default='Statistics', editable=False, primary_key=True, serialize=False),
        ),
    ]
